### PR TITLE
[BUGFIX] Always wrap ViewHelper arguments in SyntaxTree Nodes

### PR DESCRIPTION
**Pull request by bwaidelich**
This fixes a regression that prevents usage of simple types for
boolean ViewHelper arguments.

Without this fix, Fluid code like the following lead to fatal
PHP errors:
```
{f:if(condition: 1, then: 'should be rendered')}
```

Because Fluid tries to instantiate a ``BooleanNode`` without creating
the root node.

In tag syntax the argument is converted to a ``TextNode``, so the
following works without this patch:
```
<f:if condition="1" then="should be rendered" />
```
Note: This also tweaks the functional tests to actually verify the
results of the *Conditions* test cases.

### CODE REVIEW

**Comment by NamelessCoder** [comment]
If I'm understanding this correctly, would it not be more appropriate if we for example implement an `is_scalar` check or similar before creating our argument node, then allow the BooleanNode and others to be seeded with a simple scalar value that is then simply cast? I have the following concerns:

* The case is fairly unlikely - why would one ever use the syntax in question? Although I agree it *should* be supported, I think it's excessive to forcibly wrap *every* argument for *every* ViewHelper.
* Don't we have something about this in the base ViewHelper class; something about rewriting boolean nodes? Maybe that's the "more correct" place to do this?
* Does this not break if you do `{f:if(condition: unquotedReference, then: 'should be rendered')}`? E.g. rewriting `unquotedReference` to a text node because it isn't detected as a variable reference because now, as soon as it is parsed, it gets wrapped in a TextNode?

As always, please correct me if any of this is wrong!

**Comment by bwaidelich** [comment]
> The case is fairly unlikely

I agree, it's a rather rare case but I've seen code like
```
{data -> f:format.json(forceObject: 1)}
```
many a time.
```
{data -> f:format.json(forceObject: someNumber)}
```
or
```
{data -> f:format.json(forceObject: nonExistingVariable)}
```
will work, but using a number you'll get
```
Fatal Error: Argument 1 passed to BooleanNode::__construct() must implement interface NodeInterface, double given
```

> I think it's excessive to forcibly wrap every argument for every ViewHelper

Currently every argument of every ViewHelper *is* a ``NodeInterface`` already, *except* for that very case - if I'm not mistaken.

> Don't we have something about this in the base ViewHelper class

Sure, I don't care too much about the implementation of this as it's very low-level anyways. I just re-introduced the method because otherwise [some ViewHelper tests](http://134.119.11.221/flowpack.viewhelpertest/standard/index?selectedPartial=format.json&singleTestcase=7#test7) fail.
But, sure, if the ``BooleanNode`` constructor was a bit less strict and would accept other types, that should work as well.

**Comment by NamelessCoder** [comment]
I vote we should do this with the BooleanNode constructor - I spot an opportunity for improving performance in both compiled and uncompilable templates if we can stop caring about inputs for this node type.

**Comment by NamelessCoder** [comment]
Solved to the max by BooleanParser.

**Pull request closed without merging**
